/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestorproyectos;

/**
 *
 * @author ESTUDIANTE
 */
public class InformationReports extends javax.swing.JFrame {

    /**
     * Creates new form InformationReports
     */
    
    RecoverPassword recoverPass = new RecoverPassword(); 
    public InformationReports() {
        initComponents();
        recoverPass.StylePlaceHolder(txtAutorReport);
         recoverPass.StylePlaceHolder(txtDescriptionReport);
          recoverPass.StylePlaceHolder(txtDateCreationReport);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBackComments = new javax.swing.JButton();
        lbAutorReport = new javax.swing.JLabel();
        txtAutorReport = new javax.swing.JTextField();
        lbAutorReport1 = new javax.swing.JLabel();
        lbDescriptionReport = new javax.swing.JLabel();
        txtDescriptionReport = new javax.swing.JTextField();
        lbDateCreationReport = new javax.swing.JLabel();
        txtDateCreationReport = new javax.swing.JTextField();
        btnConfirmAddReports = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnBackComments.setBackground(new java.awt.Color(255, 255, 255));
        btnBackComments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fluent-emoji-high-contrast--left-arrow.png"))); // NOI18N
        btnBackComments.setBorder(null);
        btnBackComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCommentsActionPerformed(evt);
            }
        });

        lbAutorReport.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbAutorReport.setForeground(new java.awt.Color(0, 0, 0));
        lbAutorReport.setText("Autor: ");

        txtAutorReport.setText("Autor");
        txtAutorReport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAutorReportFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAutorReportFocusLost(evt);
            }
        });

        lbAutorReport1.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbAutorReport1.setForeground(new java.awt.Color(0, 0, 0));

        lbDescriptionReport.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbDescriptionReport.setForeground(new java.awt.Color(0, 0, 0));
        lbDescriptionReport.setText("Descripción:");

        txtDescriptionReport.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDescriptionReport.setText("Descripcion");
        txtDescriptionReport.setActionCommand("<Not Set>");
        txtDescriptionReport.setAutoscrolls(false);
        txtDescriptionReport.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescriptionReport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescriptionReportFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescriptionReportFocusLost(evt);
            }
        });

        lbDateCreationReport.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbDateCreationReport.setForeground(new java.awt.Color(0, 0, 0));
        lbDateCreationReport.setText("Fecha Creación: ");

        txtDateCreationReport.setText("Fecha Creacion");
        txtDateCreationReport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateCreationReportFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateCreationReportFocusLost(evt);
            }
        });

        btnConfirmAddReports.setBackground(new java.awt.Color(0, 153, 153));
        btnConfirmAddReports.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConfirmAddReports.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmAddReports.setText("Agregar");
        btnConfirmAddReports.setBorderPainted(false);
        btnConfirmAddReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmAddReportsMouseClicked(evt);
            }
        });
        btnConfirmAddReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmAddReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackComments, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lbAutorReport1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(lbAutorReport)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDateCreationReport)
                                    .addComponent(lbDescriptionReport))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescriptionReport)
                            .addComponent(txtAutorReport)
                            .addComponent(txtDateCreationReport, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(btnConfirmAddReports, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackComments, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAutorReport)
                            .addComponent(txtAutorReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(lbDescriptionReport))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescriptionReport, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAutorReport1)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDateCreationReport)
                    .addComponent(txtDateCreationReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(btnConfirmAddReports, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCommentsActionPerformed
        Reports reports = new Reports();
        reports.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackCommentsActionPerformed

    private void txtAutorReportFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAutorReportFocusGained
        if (txtAutorReport.getText().equals("Autor")) {
            txtAutorReport.setText(null);
            txtAutorReport.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtAutorReport);
        }
    }//GEN-LAST:event_txtAutorReportFocusGained

    private void txtAutorReportFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAutorReportFocusLost
        if (txtAutorReport.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtAutorReport);
            txtAutorReport.setText("Autor");
        }
    }//GEN-LAST:event_txtAutorReportFocusLost

    private void txtDescriptionReportFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionReportFocusGained
        if (txtDescriptionReport.getText().equals("Descripcion")) {
            txtDescriptionReport.setText(null);
            txtDescriptionReport.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtDescriptionReport);
        }
    }//GEN-LAST:event_txtDescriptionReportFocusGained

    private void txtDescriptionReportFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionReportFocusLost
        if (txtDescriptionReport.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtDescriptionReport);
            txtDescriptionReport.setText("Descripcion");
        }
    }//GEN-LAST:event_txtDescriptionReportFocusLost

    private void txtDateCreationReportFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateCreationReportFocusGained
         if (txtDateCreationReport.getText().equals("Fecha Creacion")) {
            txtDateCreationReport.setText(null);
            txtDateCreationReport.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtDateCreationReport);
        }
    }//GEN-LAST:event_txtDateCreationReportFocusGained

    private void txtDateCreationReportFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateCreationReportFocusLost
         if (txtDateCreationReport.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtDateCreationReport);
            txtDateCreationReport.setText("Fecha Creacion");
        }
    }//GEN-LAST:event_txtDateCreationReportFocusLost

    private void btnConfirmAddReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmAddReportsMouseClicked

    }//GEN-LAST:event_btnConfirmAddReportsMouseClicked

    private void btnConfirmAddReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmAddReportsActionPerformed

    }//GEN-LAST:event_btnConfirmAddReportsActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow(); 
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackComments;
    private javax.swing.JButton btnConfirmAddReports;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbAutorReport;
    private javax.swing.JLabel lbAutorReport1;
    private javax.swing.JLabel lbDateCreationReport;
    private javax.swing.JLabel lbDescriptionReport;
    private javax.swing.JTextField txtAutorReport;
    private javax.swing.JTextField txtDateCreationReport;
    private javax.swing.JTextField txtDescriptionReport;
    // End of variables declaration//GEN-END:variables
}
