/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestorproyectos;

/**
 *
 * @author ESTUDIANTE
 */
public class InformationComments extends javax.swing.JFrame {

    /**
     * Creates new form InformationComments
     */
    
    RecoverPassword recoverPass = new RecoverPassword(); 
    
    public InformationComments() {
        initComponents();
        recoverPass.StylePlaceHolder(txtDateComment);
        recoverPass.StylePlaceHolder(txtComment);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBackComments = new javax.swing.JButton();
        lbDateComments = new javax.swing.JLabel();
        txtComment = new javax.swing.JTextField();
        lbComments = new javax.swing.JLabel();
        txtDateComment = new javax.swing.JTextField();
        btnConfirmAddComments = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnBackComments.setBackground(new java.awt.Color(255, 255, 255));
        btnBackComments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fluent-emoji-high-contrast--left-arrow.png"))); // NOI18N
        btnBackComments.setBorder(null);
        btnBackComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCommentsActionPerformed(evt);
            }
        });

        lbDateComments.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbDateComments.setForeground(new java.awt.Color(0, 0, 0));
        lbDateComments.setText("Fecha Comentario: ");

        txtComment.setText("Comentario");
        txtComment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCommentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCommentFocusLost(evt);
            }
        });
        txtComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommentActionPerformed(evt);
            }
        });

        lbComments.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbComments.setForeground(new java.awt.Color(0, 0, 0));
        lbComments.setText("Descripción:");

        txtDateComment.setText("Fecha Comentario");
        txtDateComment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateCommentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateCommentFocusLost(evt);
            }
        });
        txtDateComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateCommentActionPerformed(evt);
            }
        });

        btnConfirmAddComments.setBackground(new java.awt.Color(0, 153, 153));
        btnConfirmAddComments.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConfirmAddComments.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmAddComments.setText("Agregar");
        btnConfirmAddComments.setBorderPainted(false);
        btnConfirmAddComments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmAddCommentsMouseClicked(evt);
            }
        });
        btnConfirmAddComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmAddCommentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackComments, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbComments)
                            .addComponent(lbDateComments))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDateComment, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(btnConfirmAddComments, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackComments, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDateComments)
                    .addComponent(txtDateComment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lbComments))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addComponent(btnConfirmAddComments, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCommentsActionPerformed
        Comments comments = new Comments();
        comments.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackCommentsActionPerformed

    private void txtCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommentActionPerformed

    private void txtDateCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateCommentActionPerformed

    private void btnConfirmAddCommentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmAddCommentsMouseClicked

    }//GEN-LAST:event_btnConfirmAddCommentsMouseClicked

    private void btnConfirmAddCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmAddCommentsActionPerformed

    }//GEN-LAST:event_btnConfirmAddCommentsActionPerformed

    private void txtDateCommentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateCommentFocusGained
        if (txtDateComment.getText().equals("Fecha Comentario")) {
            txtDateComment.setText(null);
            txtDateComment.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtDateComment);
        }
    }//GEN-LAST:event_txtDateCommentFocusGained

    private void txtCommentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCommentFocusGained
         if (txtComment.getText().equals("Comentario")) {
            txtComment.setText(null);
            txtComment.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtComment);
        }
    }//GEN-LAST:event_txtCommentFocusGained

    private void txtDateCommentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateCommentFocusLost
         if (txtDateComment.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtDateComment);
            txtDateComment.setText("Fecha Comentario");
        }
    }//GEN-LAST:event_txtDateCommentFocusLost

    private void txtCommentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCommentFocusLost
        if (txtComment.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtComment);
            txtComment.setText("Comentario");
        }
    }//GEN-LAST:event_txtCommentFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
          this.requestFocusInWindow(); 
    }//GEN-LAST:event_formWindowGainedFocus


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackComments;
    private javax.swing.JButton btnConfirmAddComments;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbComments;
    private javax.swing.JLabel lbDateComments;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextField txtDateComment;
    // End of variables declaration//GEN-END:variables
}
