/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestorproyectos;

/**
 *
 * @author ESTUDIANTE
 */
public class InformationPhases extends javax.swing.JFrame {

    /**
     * Creates new form InformationPhases
     */
    
    RecoverPassword recoverPass = new RecoverPassword(); 
    
    public InformationPhases() {
        initComponents();
        recoverPass.StylePlaceHolder(txtNamePhases);
        recoverPass.StylePlaceHolder(txtDescriptionPhases);
        recoverPass.StylePlaceHolder(txtDatePhases);
        recoverPass.StylePlaceHolder(txtStatusPhases);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBackComments = new javax.swing.JButton();
        lbStatusPhases = new javax.swing.JLabel();
        txtStatusPhases = new javax.swing.JTextField();
        lbDescriptionPhases = new javax.swing.JLabel();
        txtDescriptionPhases = new javax.swing.JTextField();
        lbDatePhases = new javax.swing.JLabel();
        txtDatePhases = new javax.swing.JTextField();
        lbNamePhases1 = new javax.swing.JLabel();
        txtNamePhases = new javax.swing.JTextField();
        btnConfirmAddPhases = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnBackComments.setBackground(new java.awt.Color(255, 255, 255));
        btnBackComments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fluent-emoji-high-contrast--left-arrow.png"))); // NOI18N
        btnBackComments.setBorder(null);
        btnBackComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCommentsActionPerformed(evt);
            }
        });

        lbStatusPhases.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbStatusPhases.setForeground(new java.awt.Color(0, 0, 0));
        lbStatusPhases.setText("Estado: ");

        txtStatusPhases.setText("Estado");
        txtStatusPhases.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStatusPhasesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStatusPhasesFocusLost(evt);
            }
        });

        lbDescriptionPhases.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbDescriptionPhases.setForeground(new java.awt.Color(0, 0, 0));
        lbDescriptionPhases.setText("Descripción:");

        txtDescriptionPhases.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDescriptionPhases.setText("Descripcion");
        txtDescriptionPhases.setActionCommand("<Not Set>");
        txtDescriptionPhases.setAutoscrolls(false);
        txtDescriptionPhases.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescriptionPhases.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescriptionPhasesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescriptionPhasesFocusLost(evt);
            }
        });

        lbDatePhases.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbDatePhases.setForeground(new java.awt.Color(0, 0, 0));
        lbDatePhases.setText("Fecha Fase: ");

        txtDatePhases.setText("Fecha Fase");
        txtDatePhases.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDatePhasesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDatePhasesFocusLost(evt);
            }
        });

        lbNamePhases1.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbNamePhases1.setForeground(new java.awt.Color(0, 0, 0));
        lbNamePhases1.setText("Nombre: ");

        txtNamePhases.setText("Nombre de Fase");
        txtNamePhases.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamePhasesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamePhasesFocusLost(evt);
            }
        });

        btnConfirmAddPhases.setBackground(new java.awt.Color(0, 153, 153));
        btnConfirmAddPhases.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConfirmAddPhases.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmAddPhases.setText("Agregar");
        btnConfirmAddPhases.setBorderPainted(false);
        btnConfirmAddPhases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmAddPhasesMouseClicked(evt);
            }
        });
        btnConfirmAddPhases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmAddPhasesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lbDescriptionPhases))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackComments, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbStatusPhases)
                            .addComponent(lbDatePhases))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDescriptionPhases, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamePhases, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(txtStatusPhases)
                    .addComponent(txtDatePhases))
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConfirmAddPhases, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(lbNamePhases1)
                    .addContainerGap(488, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackComments, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(txtNamePhases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtDescriptionPhases, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lbDescriptionPhases)))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDatePhases)
                    .addComponent(txtDatePhases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStatusPhases, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatusPhases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnConfirmAddPhases, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(lbNamePhases1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(374, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCommentsActionPerformed
        ViewProyects view = new ViewProyects();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackCommentsActionPerformed

    private void txtStatusPhasesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStatusPhasesFocusGained
        if (txtStatusPhases.getText().equals("Estado")) {
            txtStatusPhases.setText(null);
            txtStatusPhases.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtStatusPhases);
        }
    }//GEN-LAST:event_txtStatusPhasesFocusGained

    private void txtStatusPhasesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStatusPhasesFocusLost
        if (txtStatusPhases.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtStatusPhases);
            txtStatusPhases.setText("Estado");
        }
    }//GEN-LAST:event_txtStatusPhasesFocusLost

    private void txtDescriptionPhasesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionPhasesFocusGained
        if (txtDescriptionPhases.getText().equals("Descripcion")) {
            txtDescriptionPhases.setText(null);
            txtDescriptionPhases.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtDescriptionPhases);
        }
    }//GEN-LAST:event_txtDescriptionPhasesFocusGained

    private void txtDescriptionPhasesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionPhasesFocusLost
        if (txtDescriptionPhases.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtDescriptionPhases);
            txtDescriptionPhases.setText("Descripcion");
        }
    }//GEN-LAST:event_txtDescriptionPhasesFocusLost

    private void txtDatePhasesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDatePhasesFocusGained
        if (txtDatePhases.getText().equals("Fecha Fase")) {
            txtDatePhases.setText(null);
            txtDatePhases.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtDatePhases);
        }
    }//GEN-LAST:event_txtDatePhasesFocusGained

    private void txtDatePhasesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDatePhasesFocusLost
        if (txtDatePhases.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtDatePhases);
            txtDatePhases.setText("Fecha Fase");
        }
    }//GEN-LAST:event_txtDatePhasesFocusLost

    private void txtNamePhasesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamePhasesFocusGained
          if (txtNamePhases.getText().equals("Nombre de Fase")) {
            txtNamePhases.setText(null);
            txtNamePhases.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtNamePhases);
        }
    }//GEN-LAST:event_txtNamePhasesFocusGained

    private void txtNamePhasesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamePhasesFocusLost
        if (txtNamePhases.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtNamePhases);
            txtNamePhases.setText("Nombre Fase");
        }
    }//GEN-LAST:event_txtNamePhasesFocusLost

    private void btnConfirmAddPhasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmAddPhasesMouseClicked

    }//GEN-LAST:event_btnConfirmAddPhasesMouseClicked

    private void btnConfirmAddPhasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmAddPhasesActionPerformed

    }//GEN-LAST:event_btnConfirmAddPhasesActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
     this.requestFocusInWindow(); 
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackComments;
    private javax.swing.JButton btnConfirmAddPhases;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbDatePhases;
    private javax.swing.JLabel lbDescriptionPhases;
    private javax.swing.JLabel lbNamePhases1;
    private javax.swing.JLabel lbStatusPhases;
    private javax.swing.JTextField txtDatePhases;
    private javax.swing.JTextField txtDescriptionPhases;
    private javax.swing.JTextField txtNamePhases;
    private javax.swing.JTextField txtStatusPhases;
    // End of variables declaration//GEN-END:variables
}
