/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestorproyectos;

/**
 *
 * @author ESTUDIANTE
 */
public class InformationTasks extends javax.swing.JFrame {

    /**
     * Creates new form InformationTasks
     */
    RecoverPassword recoverPass = new RecoverPassword();
    public InformationTasks() {
        initComponents();
        recoverPass.StylePlaceHolder(txtNameTasks);
        recoverPass.StylePlaceHolder(txtDescriptionTasks);
        recoverPass.StylePlaceHolder(txtDateInitTasks);
        recoverPass.StylePlaceHolder(txtDateFinallyTasks);
        recoverPass.StylePlaceHolder(txtStatusTasks);
        recoverPass.StylePlaceHolder(txtPriorityTasks);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBackReports = new javax.swing.JButton();
        lbStatusTasks = new javax.swing.JLabel();
        txtNameTasks = new javax.swing.JTextField();
        lbDateInitTasks = new javax.swing.JLabel();
        txtDateInitTasks = new javax.swing.JTextField();
        lbDescriptionTasks = new javax.swing.JLabel();
        txtDescriptionTasks = new javax.swing.JTextField();
        lbDateFinallyTasks = new javax.swing.JLabel();
        txtDateFinallyTasks = new javax.swing.JTextField();
        lbNameTasks1 = new javax.swing.JLabel();
        txtStatusTasks = new javax.swing.JTextField();
        lbPriorityTasks = new javax.swing.JLabel();
        txtPriorityTasks = new javax.swing.JTextField();
        btnConfirmAddTasks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnBackReports.setBackground(new java.awt.Color(255, 255, 255));
        btnBackReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fluent-emoji-high-contrast--left-arrow.png"))); // NOI18N
        btnBackReports.setBorder(null);
        btnBackReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackReportsActionPerformed(evt);
            }
        });

        lbStatusTasks.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbStatusTasks.setForeground(new java.awt.Color(0, 0, 0));
        lbStatusTasks.setText("Estado: ");

        txtNameTasks.setText("Nombre de Tarea");
        txtNameTasks.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameTasksFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameTasksFocusLost(evt);
            }
        });

        lbDateInitTasks.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbDateInitTasks.setForeground(new java.awt.Color(0, 0, 0));
        lbDateInitTasks.setText("Fecha Inicio: ");

        txtDateInitTasks.setText("Fecha Inicio");
        txtDateInitTasks.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateInitTasksFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateInitTasksFocusLost(evt);
            }
        });

        lbDescriptionTasks.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbDescriptionTasks.setForeground(new java.awt.Color(0, 0, 0));
        lbDescriptionTasks.setText("Descripción:");

        txtDescriptionTasks.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDescriptionTasks.setText("Descripcion");
        txtDescriptionTasks.setActionCommand("<Not Set>");
        txtDescriptionTasks.setAutoscrolls(false);
        txtDescriptionTasks.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescriptionTasks.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescriptionTasksFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescriptionTasksFocusLost(evt);
            }
        });

        lbDateFinallyTasks.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbDateFinallyTasks.setForeground(new java.awt.Color(0, 0, 0));
        lbDateFinallyTasks.setText("Fecha Final: ");

        txtDateFinallyTasks.setText("Fecha Final");
        txtDateFinallyTasks.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateFinallyTasksFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateFinallyTasksFocusLost(evt);
            }
        });

        lbNameTasks1.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbNameTasks1.setForeground(new java.awt.Color(0, 0, 0));
        lbNameTasks1.setText("Nombre: ");

        txtStatusTasks.setText("Estado");
        txtStatusTasks.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStatusTasksFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStatusTasksFocusLost(evt);
            }
        });
        txtStatusTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusTasksActionPerformed(evt);
            }
        });

        lbPriorityTasks.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbPriorityTasks.setForeground(new java.awt.Color(0, 0, 0));
        lbPriorityTasks.setText("Prioridad:");

        txtPriorityTasks.setText("Prioridad");
        txtPriorityTasks.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPriorityTasksFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriorityTasksFocusLost(evt);
            }
        });
        txtPriorityTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriorityTasksActionPerformed(evt);
            }
        });

        btnConfirmAddTasks.setBackground(new java.awt.Color(0, 153, 153));
        btnConfirmAddTasks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConfirmAddTasks.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmAddTasks.setText("Agregar");
        btnConfirmAddTasks.setBorderPainted(false);
        btnConfirmAddTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmAddTasksMouseClicked(evt);
            }
        });
        btnConfirmAddTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmAddTasksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackReports, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(lbNameTasks1)
                            .addGap(33, 33, 33)
                            .addComponent(txtNameTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbDateInitTasks)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDateInitTasks))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(lbDescriptionTasks)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDescriptionTasks))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(lbStatusTasks)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtStatusTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(lbDateFinallyTasks)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtDateFinallyTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lbPriorityTasks)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtPriorityTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(btnConfirmAddTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackReports, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNameTasks1))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescriptionTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescriptionTasks))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDateInitTasks)
                    .addComponent(txtDateInitTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDateFinallyTasks)
                    .addComponent(txtDateFinallyTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStatusTasks)
                    .addComponent(txtStatusTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPriorityTasks)
                    .addComponent(txtPriorityTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmAddTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackReportsActionPerformed
        Tasks tasks = new Tasks();
        tasks.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackReportsActionPerformed

    private void txtNameTasksFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameTasksFocusGained
        if (txtNameTasks.getText().equals("Nombre de Tarea")) {
            txtNameTasks.setText(null);
            txtNameTasks.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtNameTasks);
        }
    }//GEN-LAST:event_txtNameTasksFocusGained

    private void txtNameTasksFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameTasksFocusLost
        if (txtNameTasks.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtNameTasks);
            txtNameTasks.setText("Nombre de Tarea");
        }
    }//GEN-LAST:event_txtNameTasksFocusLost

    private void txtDateInitTasksFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateInitTasksFocusGained
        if (txtDateInitTasks.getText().equals("Fecha Inicio")) {
            txtDateInitTasks.setText(null);
            txtDateInitTasks.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtDateInitTasks);
        }
    }//GEN-LAST:event_txtDateInitTasksFocusGained

    private void txtDateInitTasksFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateInitTasksFocusLost
        if (txtDateInitTasks.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtDateInitTasks);
            txtDateInitTasks.setText("Fecha Inicio");
        }
    }//GEN-LAST:event_txtDateInitTasksFocusLost

    private void txtDescriptionTasksFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionTasksFocusGained
        if (txtDescriptionTasks.getText().equals("Descripcion")) {
            txtDescriptionTasks.setText(null);
            txtDescriptionTasks.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtDescriptionTasks);
        }
    }//GEN-LAST:event_txtDescriptionTasksFocusGained

    private void txtDescriptionTasksFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionTasksFocusLost
        if (txtDescriptionTasks.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtDescriptionTasks);
            txtDescriptionTasks.setText("Descripcion");
        }
    }//GEN-LAST:event_txtDescriptionTasksFocusLost

    private void txtDateFinallyTasksFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFinallyTasksFocusGained
        if (txtDateFinallyTasks.getText().equals("Fecha Final")) {
            txtDateFinallyTasks.setText(null);
            txtDateFinallyTasks.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtDateFinallyTasks);
        }
    }//GEN-LAST:event_txtDateFinallyTasksFocusGained

    private void txtDateFinallyTasksFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFinallyTasksFocusLost
        if (txtDateFinallyTasks.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtDateFinallyTasks);
            txtDateFinallyTasks.setText("Fecha Final");
        }
    }//GEN-LAST:event_txtDateFinallyTasksFocusLost

    private void txtStatusTasksFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStatusTasksFocusGained
        if (txtStatusTasks.getText().equals("Estado")) {
            txtStatusTasks.setText(null);
            txtStatusTasks.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtStatusTasks);
        }
    }//GEN-LAST:event_txtStatusTasksFocusGained

    private void txtStatusTasksFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStatusTasksFocusLost
        if (txtStatusTasks.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtStatusTasks);
            txtStatusTasks.setText("Estado");
        }
    }//GEN-LAST:event_txtStatusTasksFocusLost

    private void txtStatusTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusTasksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusTasksActionPerformed

    private void txtPriorityTasksFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriorityTasksFocusGained
         if (txtPriorityTasks.getText().equals("Prioridad")) {
            txtPriorityTasks.setText(null);
            txtPriorityTasks.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtPriorityTasks);
        }
    }//GEN-LAST:event_txtPriorityTasksFocusGained

    private void txtPriorityTasksFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriorityTasksFocusLost
         if (txtPriorityTasks.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtPriorityTasks);
            txtPriorityTasks.setText("Prioridad");
        }
    }//GEN-LAST:event_txtPriorityTasksFocusLost

    private void txtPriorityTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriorityTasksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriorityTasksActionPerformed

    private void btnConfirmAddTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmAddTasksMouseClicked

    }//GEN-LAST:event_btnConfirmAddTasksMouseClicked

    private void btnConfirmAddTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmAddTasksActionPerformed

    }//GEN-LAST:event_btnConfirmAddTasksActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
         this.requestFocusInWindow(); 
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackReports;
    private javax.swing.JButton btnConfirmAddTasks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbDateFinallyTasks;
    private javax.swing.JLabel lbDateInitTasks;
    private javax.swing.JLabel lbDescriptionTasks;
    private javax.swing.JLabel lbNameTasks1;
    private javax.swing.JLabel lbPriorityTasks;
    private javax.swing.JLabel lbStatusTasks;
    private javax.swing.JTextField txtDateFinallyTasks;
    private javax.swing.JTextField txtDateInitTasks;
    private javax.swing.JTextField txtDescriptionTasks;
    private javax.swing.JTextField txtNameTasks;
    private javax.swing.JTextField txtPriorityTasks;
    private javax.swing.JTextField txtStatusTasks;
    // End of variables declaration//GEN-END:variables
}
