/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestorproyectos;

import ConexionSQL.ClassConexionSQLServer;
import ConexionSQL.PhasesClass;
import com.mycompany.gestorproyectos.ViewProyects;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ESTUDIANTE
 */
public class Phases extends javax.swing.JFrame {

    /**
     * Creates new form Phases
     */
    public Phases() {
        initComponents();
        cargarDatos();
    }
    
    
 private void cargarDatos() {
        ClassConexionSQLServer conexion = new ClassConexionSQLServer();
        List<PhasesClass> List = conexion.obtenerFases();

        DefaultTableModel model = (DefaultTableModel) tablePhases.getModel();
        model.setRowCount(0); 

        for (PhasesClass p : List) {
            Object[] rowData = {
                p.getIDFases(),
                p.getNombre(),
                p.getDescripcion(),
                p.getFechaFase(),
                p.getEstadoFAse()
            };
            model.addRow(rowData);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbPhasesText = new javax.swing.JLabel();
        btnBackPhases = new javax.swing.JButton();
        btnEditPhases = new javax.swing.JButton();
        btnEliminatePhases = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePhases = new javax.swing.JTable();
        btnEditPhases1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbPhasesText.setBackground(new java.awt.Color(255, 255, 255));
        lbPhasesText.setFont(new java.awt.Font("Source Serif Pro", 0, 36)); // NOI18N
        lbPhasesText.setForeground(new java.awt.Color(0, 0, 0));
        lbPhasesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPhasesText.setText("Fases");

        btnBackPhases.setBackground(new java.awt.Color(255, 255, 255));
        btnBackPhases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fluent-emoji-high-contrast--left-arrow.png"))); // NOI18N
        btnBackPhases.setBorder(null);
        btnBackPhases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackPhasesActionPerformed(evt);
            }
        });

        btnEditPhases.setBackground(new java.awt.Color(0, 153, 153));
        btnEditPhases.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnEditPhases.setForeground(new java.awt.Color(255, 255, 255));
        btnEditPhases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mdi--pen-add.png"))); // NOI18N
        btnEditPhases.setText("Agregar");
        btnEditPhases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPhasesActionPerformed(evt);
            }
        });

        btnEliminatePhases.setBackground(new java.awt.Color(0, 153, 153));
        btnEliminatePhases.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnEliminatePhases.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminatePhases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabler--trash.png"))); // NOI18N
        btnEliminatePhases.setText("Eliminar");

        tablePhases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Fase", "Nombre", "Descripción", "Fecha  Fase", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablePhases);

        btnEditPhases1.setBackground(new java.awt.Color(0, 153, 153));
        btnEditPhases1.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnEditPhases1.setForeground(new java.awt.Color(255, 255, 255));
        btnEditPhases1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nimbus--edit.png"))); // NOI18N
        btnEditPhases1.setText("Editar");
        btnEditPhases1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPhases1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEditPhases, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnEditPhases1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnEliminatePhases, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackPhases, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226)
                        .addComponent(lbPhasesText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbPhasesText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBackPhases, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminatePhases, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditPhases1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditPhases, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackPhasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackPhasesActionPerformed
        ViewProyects view = new ViewProyects();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackPhasesActionPerformed

    private void btnEditPhasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPhasesActionPerformed
       InformationPhases informationPhases = new InformationPhases(); 
        informationPhases.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditPhasesActionPerformed

    private void btnEditPhases1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPhases1ActionPerformed
         InformationPhases informationPhases = new InformationPhases(); 
        informationPhases.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditPhases1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackPhases;
    private javax.swing.JButton btnEditPhases;
    private javax.swing.JButton btnEditPhases1;
    private javax.swing.JButton btnEliminatePhases;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbPhasesText;
    private javax.swing.JTable tablePhases;
    // End of variables declaration//GEN-END:variables
}
