/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestorproyectos;

import java.awt.Color;
import java.awt.Font; 
import javax.swing.JTextField; 
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ESTUDIANTE
 */
public class RecoverPassword extends JFrame {

    /**
     * Creates new form RecoverPassword
     */
    
    
      
    public RecoverPassword() {
        initComponents();
        
        StylePlaceHolder(txtNewPass);
        StylePlaceHolder(txt_CheckNewPass);
       
    }
    
    public void StylePlaceHolder(JTextField textField){
        Font font = textField.getFont(); 
        font = font.deriveFont(Font.ITALIC); 
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    
    public void DeleteStylePlaceHolder(JTextField textField){
        
         Font font = textField.getFont(); 
        font = font.deriveFont(Font.PLAIN| Font.BOLD); 
        textField.setFont(font);
        textField.setForeground(Color.black);
    }
    
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_NewPassText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lb_CheckNewPassText = new javax.swing.JLabel();
        btn_ChangePass = new javax.swing.JButton();
        txt_CheckNewPass = new javax.swing.JPasswordField();
        txtNewPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Source Serif Pro", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("  Restablecer Contraseña");

        lb_NewPassText.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lb_NewPassText.setForeground(new java.awt.Color(0, 0, 0));
        lb_NewPassText.setText("Nueva Contraseña:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Password.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Password.png"))); // NOI18N

        lb_CheckNewPassText.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lb_CheckNewPassText.setForeground(new java.awt.Color(0, 0, 0));
        lb_CheckNewPassText.setText("Comprobar Contraseña:");

        btn_ChangePass.setBackground(new java.awt.Color(0, 153, 153));
        btn_ChangePass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_ChangePass.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChangePass.setText("Cambiar Contraseña");
        btn_ChangePass.setBorderPainted(false);
        btn_ChangePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ChangePassMouseClicked(evt);
            }
        });
        btn_ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangePassActionPerformed(evt);
            }
        });

        txt_CheckNewPass.setBackground(new java.awt.Color(255, 255, 255));
        txt_CheckNewPass.setFont(new java.awt.Font("Source Serif Pro", 0, 14)); // NOI18N
        txt_CheckNewPass.setText("Verificar Nueva Contraseña");
        txt_CheckNewPass.setBorder(null);
        txt_CheckNewPass.setEchoChar('\u0000');
        txt_CheckNewPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_CheckNewPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CheckNewPassFocusLost(evt);
            }
        });
        txt_CheckNewPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_CheckNewPassMousePressed(evt);
            }
        });

        txtNewPass.setBackground(new java.awt.Color(255, 255, 255));
        txtNewPass.setFont(new java.awt.Font("Source Serif Pro", 0, 14)); // NOI18N
        txtNewPass.setText("Nueva Contraseña");
        txtNewPass.setBorder(null);
        txtNewPass.setEchoChar('\u0000');
        txtNewPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewPassFocusLost(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ant-design--home-twotone.png"))); // NOI18N
        btnLogin.setBorderPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_CheckNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_CheckNewPassText, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_NewPassText, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btn_ChangePass)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(lb_NewPassText)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3))
                            .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(lb_CheckNewPassText)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addComponent(txt_CheckNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_ChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangePassActionPerformed
       
    }//GEN-LAST:event_btn_ChangePassActionPerformed

    private void txt_CheckNewPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_CheckNewPassMousePressed

    }//GEN-LAST:event_txt_CheckNewPassMousePressed

    private void btn_ChangePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ChangePassMouseClicked
      
    }//GEN-LAST:event_btn_ChangePassMouseClicked

    private void txtNewPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPassFocusGained
        if (txtNewPass.getText().equals("Nueva Contraseña")) {
            txtNewPass.setText(null);
            txtNewPass.requestFocus();
            txtNewPass.setEchoChar('*');
            DeleteStylePlaceHolder(txtNewPass);
            
        }
    }//GEN-LAST:event_txtNewPassFocusGained

    private void txt_CheckNewPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CheckNewPassFocusGained
        if (txt_CheckNewPass.getText().equals("Verificar Nueva Contraseña")) {
            txt_CheckNewPass.setText(null);
            txt_CheckNewPass.requestFocus();
            txt_CheckNewPass.setEchoChar('*');
            DeleteStylePlaceHolder(txt_CheckNewPass);
            
        }
    }//GEN-LAST:event_txt_CheckNewPassFocusGained

    private void txtNewPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPassFocusLost
        if (txtNewPass.getText().length() == 0 ) {
            StylePlaceHolder(txtNewPass);
            txtNewPass.setText("Nueva Contraseña");
            txtNewPass.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_txtNewPassFocusLost

    private void txt_CheckNewPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CheckNewPassFocusLost
        if (txt_CheckNewPass.getText().length() == 0) {
            StylePlaceHolder(txt_CheckNewPass);
            txt_CheckNewPass.setText("Verificar Nueva Contraseña");
            txt_CheckNewPass.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_txt_CheckNewPassFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow(); 
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Login login = new Login(); 
        
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btn_ChangePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lb_CheckNewPassText;
    private javax.swing.JLabel lb_NewPassText;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JPasswordField txt_CheckNewPass;
    // End of variables declaration//GEN-END:variables
}
