/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestorproyectos;
import ConexionSQL.Person;
import ConexionSQL.ClassConexionSQLServer;

/**
 *
 * @author ESTUDIANTE
 */

import java.awt.Color;
import java.awt.Font; 
import javax.swing.JOptionPane;
import javax.swing.JTextField; 

public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Person
     */
    
   RecoverPassword recoverPass = new RecoverPassword();
    
    public Register() {
        initComponents();
        
        recoverPass.StylePlaceHolder(txtName);
        recoverPass.StylePlaceHolder(txtFirstSurname);
        recoverPass.StylePlaceHolder(txtSecondSurname);
        recoverPass.StylePlaceHolder(txtEmail);
        recoverPass.StylePlaceHolder(txtPassword);
        recoverPass.StylePlaceHolder(txtDate);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        backgroundRegister = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbNameText = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbFirstSurnameText = new javax.swing.JLabel();
        txtFirstSurname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbSecondSurnameText = new javax.swing.JLabel();
        txtSecondSurname = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lbEmailText = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lbPasswordText = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lbDateText = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnRegister = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        Background.setBackground(new java.awt.Color(0, 153, 153));

        backgroundRegister.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Source Serif Pro", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("       Registro");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ant-design--home-twotone.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbNameText.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbNameText.setForeground(new java.awt.Color(0, 0, 0));
        lbNameText.setText("Nombre: ");

        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Source Serif Pro", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 0, 0));
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtName.setText("Nombre");
        txtName.setBorder(null);
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });

        lbFirstSurnameText.setBackground(new java.awt.Color(255, 255, 255));
        lbFirstSurnameText.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbFirstSurnameText.setForeground(new java.awt.Color(0, 0, 0));
        lbFirstSurnameText.setText("Primer Apellido: ");

        txtFirstSurname.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstSurname.setFont(new java.awt.Font("Source Serif Pro", 0, 14)); // NOI18N
        txtFirstSurname.setForeground(new java.awt.Color(0, 0, 0));
        txtFirstSurname.setText("Primer Apellido");
        txtFirstSurname.setBorder(null);
        txtFirstSurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFirstSurnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstSurnameFocusLost(evt);
            }
        });

        lbSecondSurnameText.setBackground(new java.awt.Color(255, 255, 255));
        lbSecondSurnameText.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbSecondSurnameText.setForeground(new java.awt.Color(0, 0, 0));
        lbSecondSurnameText.setText("Segundo Apellido: ");

        txtSecondSurname.setBackground(new java.awt.Color(255, 255, 255));
        txtSecondSurname.setFont(new java.awt.Font("Source Serif Pro", 0, 14)); // NOI18N
        txtSecondSurname.setForeground(new java.awt.Color(0, 0, 0));
        txtSecondSurname.setText("Segundo Apellido");
        txtSecondSurname.setBorder(null);
        txtSecondSurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSecondSurnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSecondSurnameFocusLost(evt);
            }
        });

        lbEmailText.setBackground(new java.awt.Color(255, 255, 255));
        lbEmailText.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbEmailText.setForeground(new java.awt.Color(0, 0, 0));
        lbEmailText.setText("Email: ");

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Source Serif Pro", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setText("Email");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        lbPasswordText.setBackground(new java.awt.Color(255, 255, 255));
        lbPasswordText.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbPasswordText.setForeground(new java.awt.Color(0, 0, 0));
        lbPasswordText.setText("Contraseña: ");

        lbDateText.setBackground(new java.awt.Color(255, 255, 255));
        lbDateText.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        lbDateText.setForeground(new java.awt.Color(0, 0, 0));
        lbDateText.setText("Fecha Ingreso: ");

        txtDate.setBackground(new java.awt.Color(255, 255, 255));
        txtDate.setFont(new java.awt.Font("Source Serif Pro", 0, 12)); // NOI18N
        txtDate.setForeground(new java.awt.Color(0, 0, 0));
        txtDate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDate.setText("(yyyy-MM-dd)");
        txtDate.setBorder(null);
        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateFocusLost(evt);
            }
        });
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(0, 153, 153));
        btnRegister.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Registrar");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Source Serif Pro", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword.setText("Contraseña");
        txtPassword.setBorder(null);
        txtPassword.setEchoChar('\u0000');
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        backgroundRegister.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(lbNameText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(txtName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(lbFirstSurnameText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(txtFirstSurname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(lbSecondSurnameText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(txtSecondSurname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(lbEmailText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(lbPasswordText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(jSeparator5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(lbDateText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(txtDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(jSeparator6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(btnRegister, javax.swing.JLayeredPane.DEFAULT_LAYER);
        backgroundRegister.setLayer(txtPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout backgroundRegisterLayout = new javax.swing.GroupLayout(backgroundRegister);
        backgroundRegister.setLayout(backgroundRegisterLayout);
        backgroundRegisterLayout.setHorizontalGroup(
            backgroundRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundRegisterLayout.createSequentialGroup()
                .addGroup(backgroundRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundRegisterLayout.createSequentialGroup()
                        .addContainerGap(86, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(backgroundRegisterLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(backgroundRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundRegisterLayout.createSequentialGroup()
                                .addGroup(backgroundRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4)
                                    .addComponent(txtEmail)
                                    .addComponent(jSeparator2)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFirstSurname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSecondSurname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundRegisterLayout.createSequentialGroup()
                                        .addGroup(backgroundRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbFirstSurnameText)
                                            .addComponent(lbNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbSecondSurnameText)
                                            .addComponent(lbEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(36, 36, 36))
                            .addGroup(backgroundRegisterLayout.createSequentialGroup()
                                .addGroup(backgroundRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPasswordText)
                                    .addComponent(lbDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(backgroundRegisterLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundRegisterLayout.setVerticalGroup(
            backgroundRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundRegisterLayout.createSequentialGroup()
                .addGroup(backgroundRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundRegisterLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addComponent(lbNameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbFirstSurnameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFirstSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSecondSurnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSecondSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbEmailText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPasswordText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDateText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegister)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(backgroundRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(backgroundRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow(); 
    }//GEN-LAST:event_formWindowGainedFocus

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if (txtPassword.getText().length() == 0 ) {
            recoverPass.StylePlaceHolder(txtPassword);
            txtPassword.setText("Contraseña");
            txtPassword.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if (txtPassword.getText().equals("Contraseña")) {
            txtPassword.setText(null);
            txtPassword.requestFocus();
            txtPassword.setEchoChar('*');
            recoverPass.DeleteStylePlaceHolder(txtPassword);

        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
  
    String nombre = txtName.getText();
    String apellido1 = txtFirstSurname.getText();
    String apellido2 = txtSecondSurname.getText();
    String contraseña = txtPassword.getText();
    String fechaRegistro = txtDate.getText();  
    String email = txtEmail.getText(); 
    
    
    Person nuevoRegistro = new Person (nombre, apellido1, apellido2, contraseña, fechaRegistro);
    
    
    ClassConexionSQLServer conexion = new ClassConexionSQLServer();
    
   
    if (conexion.InsertPersons(nuevoRegistro, email)) {
        JOptionPane.showMessageDialog(this, "Registro exitoso");
        Login login = new Login(); 
        login.setVisible(true);
        dispose();
        
    } else {
        JOptionPane.showMessageDialog(this, "Error al registrar la persona o el email");
    }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusLost
        if (txtDate.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtDate);
            txtDate.setText("(yyyy-MM-dd)");
        }
    }//GEN-LAST:event_txtDateFocusLost

    private void txtDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusGained
        if (txtDate.getText().equals("(yyyy-MM-dd)")) {
            txtDate.setText(null);
            txtDate.requestFocus();

            recoverPass.StylePlaceHolder(txtDate);
        }
    }//GEN-LAST:event_txtDateFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (txtEmail.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtEmail);
            txtEmail.setText("Email");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if (txtEmail.getText().equals("Email")) {
            txtEmail.setText(null);
            txtEmail.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtEmail);
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtSecondSurnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSecondSurnameFocusLost
        if (txtSecondSurname.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtSecondSurname);
            txtSecondSurname.setText("Segundo Apellido");
        }
    }//GEN-LAST:event_txtSecondSurnameFocusLost

    private void txtSecondSurnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSecondSurnameFocusGained
        if (txtSecondSurname.getText().equals("Segundo Apellido")) {
            txtSecondSurname.setText(null);
            txtSecondSurname.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtSecondSurname);
        }
    }//GEN-LAST:event_txtSecondSurnameFocusGained

    private void txtFirstSurnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstSurnameFocusLost
        if (txtFirstSurname.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtFirstSurname);
            txtFirstSurname.setText("Primer Apellido");
        }
    }//GEN-LAST:event_txtFirstSurnameFocusLost

    private void txtFirstSurnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstSurnameFocusGained
        if (txtFirstSurname.getText().equals("Primer Apellido")) {
            txtFirstSurname.setText(null);
            txtFirstSurname.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtFirstSurname);
        }
    }//GEN-LAST:event_txtFirstSurnameFocusGained

    //Focus Lost
    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        if (txtName.getText().length() == 0) {
            recoverPass.StylePlaceHolder(txtName);
            txtName.setText("Nombre");
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        if (txtName.getText().equals("Nombre")) {
            txtName.setText(null);
            txtName.requestFocus();

            recoverPass.DeleteStylePlaceHolder(txtName);
        }
    }//GEN-LAST:event_txtNameFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login = new Login();

        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JDesktopPane backgroundRegister;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbDateText;
    private javax.swing.JLabel lbEmailText;
    private javax.swing.JLabel lbFirstSurnameText;
    private javax.swing.JLabel lbNameText;
    private javax.swing.JLabel lbPasswordText;
    private javax.swing.JLabel lbSecondSurnameText;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstSurname;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSecondSurname;
    // End of variables declaration//GEN-END:variables
}
