/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestorproyectos;

import javax.swing.text.View;

/**
 *
 * @author ESTUDIANTE
 */
public class Resources extends javax.swing.JFrame {

    /**
     * Creates new form Resources
     */
    
     
    public Resources() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        backgorund = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbResourcesText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResources = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnEditResource = new javax.swing.JButton();
        btnEliminate = new javax.swing.JButton();
        btnEditResource1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgorund.setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbResourcesText.setBackground(new java.awt.Color(255, 255, 255));
        lbResourcesText.setFont(new java.awt.Font("Source Serif Pro", 0, 36)); // NOI18N
        lbResourcesText.setForeground(new java.awt.Color(0, 0, 0));
        lbResourcesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbResourcesText.setText("Recursos");

        tableResources.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Recursos", "Nombre", "Tipo Recurso", "Cantidad Recursos", "Costos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableResources);
        if (tableResources.getColumnModel().getColumnCount() > 0) {
            tableResources.getColumnModel().getColumn(1).setMinWidth(60);
            tableResources.getColumnModel().getColumn(1).setMaxWidth(60);
        }

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fluent-emoji-high-contrast--left-arrow.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnEditResource.setBackground(new java.awt.Color(0, 153, 153));
        btnEditResource.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnEditResource.setForeground(new java.awt.Color(255, 255, 255));
        btnEditResource.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nimbus--edit.png"))); // NOI18N
        btnEditResource.setText("Editar");
        btnEditResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditResourceActionPerformed(evt);
            }
        });

        btnEliminate.setBackground(new java.awt.Color(0, 153, 153));
        btnEliminate.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnEliminate.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabler--trash.png"))); // NOI18N
        btnEliminate.setText("Eliminar");

        btnEditResource1.setBackground(new java.awt.Color(0, 153, 153));
        btnEditResource1.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnEditResource1.setForeground(new java.awt.Color(255, 255, 255));
        btnEditResource1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mdi--pen-add.png"))); // NOI18N
        btnEditResource1.setText("Agregar");
        btnEditResource1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditResource1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbResourcesText, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(318, 318, 318))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 75, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEditResource1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(btnEditResource, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(btnEliminate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbResourcesText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditResource, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditResource1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgorundLayout = new javax.swing.GroupLayout(backgorund);
        backgorund.setLayout(backgorundLayout);
        backgorundLayout.setHorizontalGroup(
            backgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgorundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        backgorundLayout.setVerticalGroup(
            backgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgorundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgorund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgorund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      ViewProyects view = new ViewProyects(); 
      view.setVisible(true);
      dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditResource1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditResource1ActionPerformed
       InformationResources informationResource = new InformationResources(); 
        informationResource.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditResource1ActionPerformed

    private void btnEditResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditResourceActionPerformed
         InformationResources informationResource = new InformationResources(); 
        informationResource.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditResourceActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgorund;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEditResource;
    private javax.swing.JButton btnEditResource1;
    private javax.swing.JButton btnEliminate;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbResourcesText;
    private javax.swing.JTable tableResources;
    // End of variables declaration//GEN-END:variables
}
