/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestorproyectos;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.JFrame;

/**
 *
 * @author ESTUDIANTE
 */
public class ViewProyects extends JFrame {

    
     Resources resources = new Resources();
     Tasks task = new Tasks(); 
     Reports report = new Reports(); 
     Phases phase = new Phases();
     Comments comment = new Comments(); 
    /**
     * Creates new form ViewProyects
     */
    public ViewProyects() {
        initComponents();
    }
    
    public void StylePlaceHolder(JTextField textField){
        Font font = textField.getFont(); 
        font = font.deriveFont(Font.ITALIC); 
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    
    public void DeleteStylePlaceHolder(JTextField textField){
        
         Font font = textField.getFont(); 
        font = font.deriveFont(Font.PLAIN| Font.BOLD); 
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnResources = new javax.swing.JButton();
        btnTasks = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnPhases = new javax.swing.JButton();
        btnComments = new javax.swing.JButton();
        lbNameProyect = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnResources.setBackground(new java.awt.Color(0, 153, 153));
        btnResources.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnResources.setForeground(new java.awt.Color(255, 255, 255));
        btnResources.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nimbus--tools.png"))); // NOI18N
        btnResources.setText("Recursos");
        btnResources.setBorder(null);
        btnResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResourcesActionPerformed(evt);
            }
        });

        btnTasks.setBackground(new java.awt.Color(0, 153, 153));
        btnTasks.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnTasks.setForeground(new java.awt.Color(255, 255, 255));
        btnTasks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fluent--tasks-app-20-regular.png"))); // NOI18N
        btnTasks.setText("Tareas");
        btnTasks.setBorder(null);
        btnTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTasksActionPerformed(evt);
            }
        });

        btnReports.setBackground(new java.awt.Color(0, 153, 153));
        btnReports.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mingcute--task-line.png"))); // NOI18N
        btnReports.setText("Informes");
        btnReports.setBorder(null);
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnPhases.setBackground(new java.awt.Color(0, 153, 153));
        btnPhases.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnPhases.setForeground(new java.awt.Color(255, 255, 255));
        btnPhases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/la--list.png"))); // NOI18N
        btnPhases.setText("Fases");
        btnPhases.setBorder(null);
        btnPhases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhasesActionPerformed(evt);
            }
        });

        btnComments.setBackground(new java.awt.Color(0, 153, 153));
        btnComments.setFont(new java.awt.Font("Source Serif Pro", 0, 18)); // NOI18N
        btnComments.setForeground(new java.awt.Color(255, 255, 255));
        btnComments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eva--message-square-outline.png"))); // NOI18N
        btnComments.setText("Comentarios");
        btnComments.setBorder(null);
        btnComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommentsActionPerformed(evt);
            }
        });

        lbNameProyect.setBackground(new java.awt.Color(255, 255, 255));
        lbNameProyect.setFont(new java.awt.Font("Source Serif Pro", 0, 36)); // NOI18N
        lbNameProyect.setForeground(new java.awt.Color(0, 0, 0));
        lbNameProyect.setText("Nombre Proyecto");
        lbNameProyect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fluent-emoji-high-contrast--left-arrow.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNameProyect, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btnPhases, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(btnComments, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnResources, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbNameProyect))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResources, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPhases, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComments, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResourcesActionPerformed
        resources.setVisible(true);
                    dispose();
    }//GEN-LAST:event_btnResourcesActionPerformed

    private void btnTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTasksActionPerformed
      task.setVisible(true);
      dispose();
    }//GEN-LAST:event_btnTasksActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        report.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnPhasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhasesActionPerformed
        phase.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_btnPhasesActionPerformed

    private void btnCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentsActionPerformed
       comment.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCommentsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Home home = new Home();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnComments;
    private javax.swing.JButton btnPhases;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnResources;
    private javax.swing.JButton btnTasks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNameProyect;
    // End of variables declaration//GEN-END:variables
}
